# Numpy tutorial

NumPy empowers rapid computation in Python by leveraging an underlying C implementation, resulting in exceptional speed. Its primary asset is the `ndarray` object, ensuring homogeneity of data types within arrays, thereby requiring elements to be of a singular data type. This design contributes to the efficiency and performance that makes NumPy a powerful tool for numerical operations in Python.

In [18]:
import numpy as np

vector = np.array([1, 2, 3, 4])
print("Vector: {}".format(vector))
# Every array will have a shape. That is, its dimensions
print("Shape: {}".format(vector.shape))
# Print number of dimensions
print("Dim: {}".format(vector.ndim))
print("Data type: {}".format(vector.dtype))

Vector: [1 2 3 4]
Shape: (4,)
Dim: 1
Data type: int32


Numpy utilizes representations with dimensions specified as 

`(depth, rows, columns)`. 

Therefore, a 3D array characterized by 3 rows, 2 columns, and 2 depth will have the shape `(2, 3, 2)`.

In [5]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
v.shape = (2, 3, 2)
print(v)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
v = np.zeros((2, 3, 2))
print(v)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


## arange

The [`arange` function](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) is similar to Python's `range` function. If the data type is not specified, in many cases it will be `np.foat64`. 

**Exercice** : create an array with integers from 0 to 10, then from 10 to 20 

In [7]:
a = np.arange(0,11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
a = np.arange(10,21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


## zeros, zeros_like

[`zeros(dim)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) will return a np.array of `dim` dimensions initialised with 0. Note that `dim` should be a `tuple`. 

[`zeros_like(array)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html) will return a np.array of same dimensions as of `array` initialised with zeros. 

**Exercice** : create a (4,4) array with zeros and then an array similar to `array_example` but with zeros everywhere


In [9]:
print("Zeros")
a = np.zeros((4,4))
print("A: {}".format(a))

array_example = np.array([[3., 4.], [9, 0.]])
b = np.zeros_like(array_example)
print("B: {}".format(b))

Zeros
A: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
B: [[0. 0.]
 [0. 0.]]


`ones` and `ones_like` share identical functionality, initializing arrays with ones. Similarly, `empty` and `empty_like` create numpy arrays without initialization (resulting in faster execution), defaulting to garbage values for all array elements.

**Exercice** : do the previous exercice with those functions


In [10]:
print("\nOnes")

a = np.ones((4,4))
print("A: {}".format(a))

array_example = np.array([[3., 4.], [9, 0.]])
b = np.ones_like(array_example)
print("B: {}".format(b))

print("\nEmpty")

c = np.empty((4,4))
print("C: {}".format(c))

array_example = np.array([[3., 4.], [9, 0.]])
d = np.empty_like(array_example)
print("D: {}".format(d))


Ones
A: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
B: [[1. 1.]
 [1. 1.]]

Empty
C: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
D: [[3. 4.]
 [9. 0.]]


## astype

The [`astype` method](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html) will convert one data type to another. Also note that `astype` will __create a new copy of the input array (even if the data type is same)__. 

**Exercice** : convert the array below into `int` type. 

In [11]:
a = np.array([1, 2, 3, 4.5, 6.7])
print("A: {}, dtype: {}".format(a, a.dtype))
b = a.astype(int)
print("B: {}, dtype: {}".format(b, b.dtype))

A: [1.  2.  3.  4.5 6.7], dtype: float64
B: [1 2 3 4 6], dtype: int32


## Vectorization and vector-scalar operations

Utilizing for loops in code not only introduces error vulnerabilities but also proves inefficient. A more effective approach involves leveraging NumPy operations to replace these for loops, a technique known as vectorization.

#### Using operations on same sized arrays produce element wise operations. 

It is possible to do basic operations with numpy

**Exercice** : create additions, substractions, multiplications out of the two arrays below

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])

# Addition
c = 
print(c)

# Substraction
d = 
print(d)

# Multiplication
e = 
print(e)

[[5 7 9]
 [5 7 9]]
[[ 4 10 18]
 [ 4 10 18]]
[[-3 -3 -3]
 [ 3  3  3]]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])

# Addition
c = a + b
print(c)

# Substraction
d = a - b
print(d)

# Multiplication
e = a*b
print(e)

[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [ 3  3  3]]
[[ 4 10 18]
 [ 4 10 18]]


Using scalars with vectors will produce element wise operations

**Exercice** : create addition, substraction, multiplication, division out of the two arrays below

In [14]:
a = 3
b = np.array([[1, 2, 3], [4, 5, 6]])

c = a +b
print(c)

d = a - b
print(d)

e = a*b
print(e)

f = a/b
print(f)

[[4 5 6]
 [7 8 9]]
[[ 2  1  0]
 [-1 -2 -3]]
[[ 3  6  9]
 [12 15 18]]
[[3.   1.5  1.  ]
 [0.75 0.6  0.5 ]]


## Slicing 

In NumPy, [slicing](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding) refers to extracting a portion of an array by specifying a range of indices. It allows you to create a new view of the array without copying data, facilitating efficient access and manipulation of specific elements or subarrays. Slicing in NumPy involves using the colon (`:`) operator to define the start, stop, and step parameters for the desired selection.

You can slice by following the syntax:
```
array[start_index:end_index] 
```
For n-dimensional array, you can slice with:
```
array[start_index:end_index, start_index:end_index] 
```

Slicing NumPy arrays is similar to that of Python lists. One main distinction in Python list and NumPy array is that the slice __is not the copy, but the original array. Hence, if any operations on the slice will be reflected in the original array.__

**Exercice** : slice the array below and assign to indexes from 10 to 15 the value 5.

In [15]:
a = np.arange(20)
print(a)
a[10:15] = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9  5  5  5  5  5 15 16 17 18 19]


If you want to avoid above scenario, you can use `copy()`

**Exercice**: use the function `copy()` to create a separate array

In [16]:
a = np.arange(20)
print(a)
b = a.copy()
b = 5
# value in the original array doesn't change
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Slicing by `:` will take the entire axis. So:
```
1. arr2d[:, 0]         Will return array of shape (3, )
2. arr2d[:, :1]        Will return array of shape (3, 1)
```

In [23]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d[:, 0]

array([1, 4, 7])

## Boolean indexing

[Boolean indexing](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing) in NumPy involves using boolean arrays to select elements based on a specified condition. This method creates a new array containing only the elements that satisfy the given boolean condition. It provides a powerful and concise way to filter and manipulate data within NumPy arrays.

Using boolean indexing, you can use it to filter or check if any entries have any specific values. 

**Exercice** : use boolean indexing to create a boolean arrays (we call them masks) for indexing.

In [3]:
a = np.array(["Mayur", "is", "an", "awesome", "coder"])
mask = (a == "Mayur")
print(mask) # Returns boolean array

[ True False False False False]


**Exercice**: obtain an array from the array `a` that has all values except "Mayur"

In [5]:
# lists entry where value != "Mayur" 
filtered_a = [x for x in a if x != "Mayur"]
print(filtered_a)

['is', 'an', 'awesome', 'coder']


__You can use `|` for `or` and `&` for `and` but not Python's `and`, `or` will not work with NumPy's indexing. __

**Exercice**: create booleans masks with the or and and logical conditions, on variables "Mayur" and "coder"

In [9]:
# Boolean mask for "Mayur" or "coder"
mask_or = np.logical_or(a == "Mayur", a == "coder")
print(mask_or)

[ True False False False  True]


In [10]:
# Boolean mask for "Mayur" and "coder"
mask_and = np.logical_and(a == "Mayur", a == "coder")
print(mask_and)

[False False False False False]


## Transposing

You can obtains the [transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) of your matring using `matrix.T` where `matrix` is your matrix name. 

**Exercice**: create the transposition of the matrix below

In [11]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
a_transposed = a.T
print(a_transposed)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


## Matrix multiplication

In NumPy, matrix multiplication can be performed using the [`np.dot()`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) function or the `@` operator. You need to check that the shapes are compatible.

**Exercice**: do the matrix multiplication

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.dot()
result_dot = np.dot(a, b)

# Matrix multiplication using @ operator
result_at = a @ b

print(result_dot)
print(result_at)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Universal Functions
NumPy has variety of functions that can be applied to scalars as well as vectors. Some examples are sqrt, exp, log, log10, sin, cos, arcsin etc. 

In [21]:
a = 20
b = np.random.rand(2, 2)
print(np.exp(a))
print(np.exp(b))

485165195.4097903
[[1.20490523 1.76000102]
 [1.01048349 2.70105749]]


**Exercice**: create other examples with sqrt, log, sin

In [13]:
# Square root of a scalar
sqrt_a = np.sqrt(a)
print("Square root of", a, ":", sqrt_a)

# Square root of a matrix
sqrt_b = np.sqrt(b)
print("\nSquare root of matrix B:\n", sqrt_b)

# Natural logarithm of a scalar
log_a = np.log(a)
print("\nNatural logarithm of", a, ":", log_a)

# Natural logarithm of a matrix
log_b = np.log(b)
print("\nNatural logarithm of matrix B:\n", log_b)

# Sine of a scalar (in radians)
sin_a = np.sin(a)
print("\nSine of", a, ":", sin_a)

# Sine of a matrix (in radians)
sin_b = np.sin(b)
print("\nSine of matrix B:\n", sin_b)

Square root of [[1 2]
 [3 4]] : [[1.         1.41421356]
 [1.73205081 2.        ]]

Square root of matrix B:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]

Natural logarithm of [[1 2]
 [3 4]] : [[0.         0.69314718]
 [1.09861229 1.38629436]]

Natural logarithm of matrix B:
 [[1.60943791 1.79175947]
 [1.94591015 2.07944154]]

Sine of [[1 2]
 [3 4]] : [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

Sine of matrix B:
 [[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]


## meshgrid

One of the most useful function is [meshgrid](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html). It's used to visualize data boundaries of your classifier. What you do is train your classifier, then create a meshgrid of every pixel in the plot, and then classify the pixel. When you give the pixel a specific color according to the labelled class you can clearly visualize the boundaries. 

Using meshgrid requires three steps. 
1. Create xs (1D array)
2. Create ys (1D array)
3. Create meshgrid (2D array) which corresponds to every pixel in the graph.  

In [14]:
xs = np.linspace(1, 10, 100)
ys = np.linspace(1, 10, 100)
xx, yy = np.meshgrid(xs, ys)
# plot with xx and yy
print(xx, yy)

[[ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 ...
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]
 [ 1.          1.09090909  1.18181818 ...  9.81818182  9.90909091
  10.        ]] [[ 1.          1.          1.         ...  1.          1.
   1.        ]
 [ 1.09090909  1.09090909  1.09090909 ...  1.09090909  1.09090909
   1.09090909]
 [ 1.18181818  1.18181818  1.18181818 ...  1.18181818  1.18181818
   1.18181818]
 ...
 [ 9.81818182  9.81818182  9.81818182 ...  9.81818182  9.81818182
   9.81818182]
 [ 9.90909091  9.90909091  9.90909091 ...  9.90909091  9.90909091
   9.90909091]
 [10.         10.         10.         ... 10.         10.
  10.        ]]


# where

[`np.where` is a NumPy function](https://numpy.org/doc/stable/reference/generated/numpy.where.html) that returns the indices where a specified condition is true in an array, allowing for conditional selection or assignment of values. Concretly, if you have 3 arrays x, y, and condition then, `np.where` is replacement for using:
```
if condition: 
    use x
else:
    use y
```

In [23]:
x = [0, -1, 2, 3, -4, -5]
y = [9, 3, 4, 11, 2, 3]
condition = [True, False, True, True, False, True]
np.where(condition, x, y)

array([ 0,  3,  2,  3,  2, -5])

**Exercice**: create a condition `x<y` and apply it to the previous arrays `x` and `y`

In [25]:
# Create a condition x < y
condition2 = x < y

# Apply the condition as a mask
np.where(condition2, x, y)


array([ 0, -1,  2,  3, -4, -5])

## mean, sum, std
NumPy provides variety of functions for statistical use. You can furthermore specify the axis you want to reduce. 

**Exercice**: Use the [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) and [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html) functions on the array below 

In [26]:
a = np.random.rand(3, 3)
# Calculate mean along each axis
mean_axis_0 = np.mean(a, axis=0)  # mean along axis 0 (columns)
mean_axis_1 = np.mean(a, axis=1)  # mean along axis 1 (rows)

# Calculate sum along each axis
sum_axis_0 = np.sum(a, axis=0)  # sum along axis 0 (columns)
sum_axis_1 = np.sum(a, axis=1)  # sum along axis 1 (rows)

# Calculate standard deviation along each axis
std_axis_0 = np.std(a, axis=0)  # std along axis 0 (columns)
std_axis_1 = np.std(a, axis=1)  # std along axis 1 (rows)

# Display the results
print("Original array:\n", a)
print("\nMean along axis 0 (columns):\n", mean_axis_0)
print("\nMean along axis 1 (rows):\n", mean_axis_1)
print("\nSum along axis 0 (columns):\n", sum_axis_0)
print("\nSum along axis 1 (rows):\n", sum_axis_1)
print("\nStandard deviation along axis 0 (columns):\n", std_axis_0)
print("\nStandard deviation along axis 1 (rows):\n", std_axis_1)

Original array:
 [[0.8926709  0.06280408 0.87334722]
 [0.27517382 0.40834197 0.04336933]
 [0.54995058 0.02862864 0.87614481]]

Mean along axis 0 (columns):
 [0.57259843 0.16659156 0.59762046]

Mean along axis 1 (rows):
 [0.6096074  0.24229504 0.48490801]

Sum along axis 0 (columns):
 [1.7177953  0.49977469 1.79286137]

Sum along axis 1 (rows):
 [1.8288222  0.72688513 1.45472403]

Standard deviation along axis 0 (columns):
 [0.25260028 0.17151178 0.39191639]

Standard deviation along axis 1 (rows):
 [0.38672881 0.15080234 0.34904042]
